import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/ui/organisms/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clothes Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-slate-800`}>
        {/* <Navbar/> */}
        <Navbar />
        <section className="mx-auto max-w-2xl px-8 sm:px-6 sm:py-4 md:max-w-4xl lg:max-w-7xl">
          {children}
        </section>
        <footer className="bg-slate-900 text-white"></footer>
      </body>
    </html>
  );
}
